* Jour 6 : Garde Gallivant 

* Partie 1
Les historiens utilisent à nouveau leur appareil sophistiqué , cette fois pour vous emmener tous au laboratoire de fabrication du prototype de combinaison du pôle Nord... en l'an 1518 ! Il s'avère qu'avoir un accès direct à l'histoire est très pratique pour un groupe d'historiens.

Il faudra néanmoins faire attention aux paradoxes temporels, et il sera donc important d'éviter toute personne de 1518 pendant que les historiens recherchent le chef. Malheureusement, un seul garde patrouille dans cette partie du laboratoire.

Peut-être pourriez-vous déterminer à l'avance où le garde ira afin que les historiens puissent effectuer des recherches en toute sécurité ?

Vous commencez par faire une carte (votre entrée de puzzle) de la situation. Par exemple :
#+begin_example
....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
#+end_example
La carte montre la position actuelle du garde avec ^(pour indiquer que le garde est actuellement tourné vers le haut depuis la perspective de la carte). Toutes les obstructions - caisses, bureaux, réacteurs alchimiques, etc. - sont indiquées par #.

Les gardes du laboratoire du 1518 suivent un protocole de patrouille très strict qui consiste à suivre à plusieurs reprises ces étapes :

S'il y a quelque chose directement devant vous, tournez à droite à 90 degrés.
Sinon, faites un pas en avant.
En suivant le protocole ci-dessus, le garde monte plusieurs fois jusqu'à atteindre un obstacle (dans ce cas, une pile de prototypes de combinaisons défaillantes) :
#+begin_example
....#.....
....^....#
..........
..#.......
.......#..
..........
.#........
........#.
#.........
......#...
#+end_example
Parce qu'il y a maintenant un obstacle devant le garde, elle tourne à droite avant de continuer tout droit dans sa nouvelle direction :
#+begin_example
....#.....
........>#
..........
..#.......
.......#..
..........
.#........
........#.
#.........
......#...
#+end_example
Atteignant un autre obstacle (une bobine de plusieurs polymères très longs), elle tourne à nouveau à droite et continue vers le bas :
#+begin_example
....#.....
.........#
..........
..#.......
.......#..
..........
.#......v.
........#.
#.........
......#...
#+end_example
Ce processus continue pendant un certain temps, mais le garde finit par quitter la zone cartographiée (après être passé devant un réservoir de solvant universel) :
#+begin_example
....#.....
.........#
..........
..#.......
.......#..
..........
.#........
........#.
#.........
......#v..
#+end_example
En prédisant l'itinéraire du garde, vous pouvez déterminer quelles positions spécifiques du laboratoire se trouveront sur le chemin de la patrouille. En incluant la position de départ du garde , les positions visitées par le garde avant de quitter la zone sont marquées par un X:
#+begin_example
....#.....
....XXXXX#
....X...X.
..#.X...X.
..XXXXX#X.
..X.X.X.X.
.#XXXXXXX.
.XXXXXXX#.
#XXXXXXX..
......#X..
#+end_example
Dans cet exemple, le garde visitera 41des positions distinctes sur votre carte.

Prévoyez le chemin du garde. Combien de positions distinctes le garde visitera-t-il avant de quitter la zone cartographiée ?

** Votre réponse à l'énigme était 5305.


* Partie 2

Alors que les historiens commencent à travailler sur l'itinéraire de patrouille des gardes, vous empruntez leur appareil sophistiqué et sortez du laboratoire. Depuis la sécurité d'un placard de fournitures, vous voyagez dans le temps à travers les derniers mois et enregistrez l'état nocturne du poste de garde du laboratoire sur les murs du placard.

De retour après ce qui semble n'être que quelques secondes auprès des Historiens, ils expliquent que la zone de patrouille des gardes est tout simplement trop grande pour qu'ils puissent fouiller le laboratoire en toute sécurité sans se faire prendre.

Heureusement, ils sont presque certains que l'ajout d'un seul nouvel obstacle ne provoquera pas de paradoxe temporel. Ils aimeraient placer le nouvel obstacle de telle manière que le garde se retrouve coincé dans une boucle , ce qui rendrait le reste du laboratoire sûr pour la recherche.

Pour réduire au minimum les risques de créer un paradoxe temporel, les historiens aimeraient connaître toutes les positions possibles pour une telle obstruction. La nouvelle obstruction ne peut pas être placée à la position de départ du garde - le garde est là en ce moment et le remarquerait.

Dans l'exemple ci-dessus, il n'y a que 6différentes positions où une nouvelle obstruction entraînerait le blocage du garde dans une boucle. Les diagrammes de ces six situations servent Oà marquer la nouvelle obstruction, |à montrer une position où le garde se déplace vers le haut/bas, -à montrer une position où le garde se déplace vers la gauche/droite et +à montrer une position où le garde se déplace à la fois vers le haut/bas et vers la gauche/droite.

Option 1, placer une presse à imprimer à côté de la position de départ du garde :
#+begin_example
....#.....
....+---+#
....|...|.
..#.|...|.
....|..#|.
....|...|.
.#.O^---+.
........#.
#.........
......#...
#+end_example
Option deux, placez une pile de prototypes de combinaisons défaillantes dans le quadrant inférieur droit de la zone cartographiée :

#+begin_example
....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
......O.#.
#.........
......#...
#+end_example
Option trois, placez une caisse de tissu prototype compressé à côté du bureau debout dans le quadrant inférieur droit :
#+begin_example
....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
.+----+O#.
#+----+...
......#...
#+end_example
Option quatre, placez un rétroencabulateur alchimique près du coin inférieur gauche :
#+begin_example
....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
..|...|.#.
#O+---+...
......#...
#+end_example
Option cinq, placez plutôt le rétroencabulateur alchimique un peu à droite :
#+begin_example
....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
....|.|.#.
#..O+-+...
......#...
#+end_example
Option six, placez un réservoir de colle souveraine juste à côté du réservoir de solvant universel :
#+begin_example
....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
.+----++#.
#+----++..
......#O..
#+end_example
Peu importe ce que vous choisissez d'utiliser comme obstacle tant que vous et les Historiens pouvez le mettre en place sans que le garde ne s'en aperçoive. L'important est d'avoir suffisamment d'options pour pouvoir en trouver une qui minimise les paradoxes temporels, et dans cet exemple, il existe 6différentes positions que vous pouvez choisir.

Vous devez bloquer la garde dans une boucle en ajoutant une seule nouvelle obstruction. Combien de positions différentes pourriez-vous choisir pour cette obstruction ?

** Votre réponse à l'énigme était 2143.

Les deux parties de ce puzzle sont complètes ! Elles fournissent deux étoiles d'or : **
